node:
    build: docker/node
    volumes_from:
        - data

webpack:
    restart: always
    build: docker/node
    entrypoint: bin/gulp webpack:server
    expose:
        - "3000"
    volumes_from:
        - data
    ports:
        - "50000:3000"

data:
    image: busybox
    volumes:
        - .:/var/www/html
