#!/bin/bash

_kill_procs() {
  kill -TERM $chromium
  wait $chromium
  kill -TERM $xvfb
  wait $xvfb
  kill -TERM $x11vnc
}

# Setup a trap to catch SIGTERM and relay it to child processes
trap _kill_procs SIGTERM

XVFB_WHD=${XVFB_WHD:-1280x720x16}

# Start Xvfb
Xvfb :99 -ac -screen 0 $XVFB_WHD -nolisten tcp &
xvfb=$!

export DISPLAY=:99

echo "Starting X11VNC Server..."
x11vnc -display :99 &
x11vnc=$!

echo "Starting Google Chrome..."
google-chrome-stable --user-data-dir=/chrome-data --no-sandbox $@ &
chromium=$!

wait $chromium
wait $xvfb
wait $x11vnc
